language: r
sudo: required
dist: xenial
cache: packages
latex: true

# we cannot install lwgeom via apt as it requires v2.4.0 but only v2.1.2 is in the repos
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
      - netcdf-bin # for stars netcdf dep

r:
  - release
  - devel

before_install: R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes"); if (!requireNamespace("curl")) install.packages("curl"); if (!requireNamespace("rgdal")) install.packages("rgdal"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
script: R -q -e 'tic::script()'

before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: develop
     condition:
       - $TRAVIS_PULL_REQUEST = false
       - $TRAVIS_EVENT_TYPE != cron
       - $TRAVIS_R_VERSION_STRING = release

after_success: R -q -e 'tic::after_success()'
