language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
      - postgresql-server-dev-all

r:
  - release
  - devel

r_packages:
  - lwgeom

r_github_packages:
  - r-spatial/stars

warnings_are_errors: false

before_install:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.6.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.6.tar.gz)
  - (cd /tmp/postgis-2.3.6 ; ./configure; make; sudo make install)
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'

script: R -q -e 'tic::script()'

after_success: R -q -e 'tic::after_success()'

before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: master
     condition:
       - $TRAVIS_PULL_REQUEST = false
       - $TRAVIS_EVENT_TYPE != cron
